services:
  mysql:
    image: mysql:8.0
    container_name: php-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: appdb
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  php-app:
    build: ./php-app
    container_name: php-app
    ports:
      - "8081:80"
    environment:
      DB_HOST: mysql
      DB_NAME: appdb
      DB_USER: app
      DB_PASS: app
      API_URL: http://host.docker.internal:8081
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  node-gateway:
    build: ./node-gateway
    container_name: node-gateway
    ports:
      - "3000:3000"
    environment:
      PHP_API_URL: http://php-app
    depends_on:
      php-app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  mysql-data:
