apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  root-password: {{ .Values.env.db.rootPassword | quote }}
  username: {{ .Values.env.db.user | quote }}
  password: {{ .Values.env.db.pass | quote }}
